# GENERATED BY GPT

# =========================================================
# Common Python Data Structure Conventions for Interviews
# =========================================================

from collections import deque, defaultdict, Counter
import heapq


# =========================================================
# STACK
# =========================================================
# LIFO (Last In First Out)

stack = []

stack.append(10)     # push
stack.append(20)

top = stack[-1]      # peek/top
value = stack.pop()  # pop

# Complexity:
# append -> O(1)
# pop    -> O(1)


# =========================================================
# QUEUE
# =========================================================
# FIFO (First In First Out)

q = deque()

q.append(10)         # enqueue
q.append(20)

front = q[0]         # front element
value = q.popleft()  # dequeue

# Complexity:
# append    -> O(1)
# popleft   -> O(1)


# =========================================================
# DEQUE
# =========================================================
# Double-ended queue

dq = deque()

dq.append(10)        # push right
dq.appendleft(5)     # push left

dq.pop()             # pop right
dq.popleft()         # pop left


# =========================================================
# HASHMAP / DICTIONARY
# =========================================================

mp = {}

# insert/update
mp["apple"] = 5

# access
x = mp["apple"]

# safe access
x = mp.get("banana")

# safe access with default
x = mp.get("banana", 0)

# existence check
if "apple" in mp:
    pass

# iteration
for key in mp:
    pass

for value in mp.values():
    pass

for key, value in mp.items():
    pass

# Common naming conventions
freq = {}
memo = {}
index_map = {}
old_to_copy = {}


# =========================================================
# SET
# =========================================================

seen = set()

seen.add(5)

if 5 in seen:
    pass

seen.remove(5)     # crashes if missing
seen.discard(5)    # safe remove

# Complexity:
# insert -> O(1)
# lookup -> O(1)


# =========================================================
# PRIORITY QUEUE / MIN HEAP
# =========================================================

heap = []

heapq.heappush(heap, 10)
heapq.heappush(heap, 3)
heapq.heappush(heap, 7)

smallest = heapq.heappop(heap)

# peek smallest
smallest = heap[0]

# Complexity:
# push -> O(log n)
# pop  -> O(log n)


# =========================================================
# MAX HEAP CONVENTION
# =========================================================
# Python only directly supports min heaps

max_heap = []

heapq.heappush(max_heap, -10)
heapq.heappush(max_heap, -3)

largest = -heapq.heappop(max_heap)


# =========================================================
# COUNTER
# =========================================================
# Frequency map shortcut

nums = [1, 2, 2, 3, 3, 3]

freq = Counter(nums)

count_of_3 = freq[3]

most_common = freq.most_common(2)


# =========================================================
# DEFAULTDICT
# =========================================================
# Automatically creates default values

mp = defaultdict(int)

mp[5] += 1

# Common defaults:
# defaultdict(int)
# defaultdict(list)
# defaultdict(set)


# =========================================================
# GRAPH (Adjacency List)
# =========================================================

graph = defaultdict(list)

graph[1].append(2)
graph[1].append(3)

# Weighted graph
weighted_graph = defaultdict(list)

weighted_graph[1].append((2, 5))   # node 2 with weight 5


# =========================================================
# BFS TEMPLATE
# =========================================================

q = deque([0])
visited = set([0])

while q:
    node = q.popleft()

    for nei in graph[node]:
        if nei not in visited:
            visited.add(nei)
            q.append(nei)


# =========================================================
# DFS RECURSIVE TEMPLATE
# =========================================================

def dfs(node):
    if not node:
        return

    dfs(node.left)
    dfs(node.right)


# =========================================================
# DFS ITERATIVE TEMPLATE
# =========================================================

stack = [0]

while stack:
    node = stack.pop()


# =========================================================
# MONOTONIC STACK TEMPLATE
# =========================================================

nums = [2, 1, 5, 3]

stack = []

for x in nums:

    while stack and stack[-1] < x:
        stack.pop()

    stack.append(x)


# =========================================================
# COMMON INTERVIEW IMPORTS
# =========================================================

# from collections import deque, defaultdict, Counter
# import heapq