# GENERATED BY GPT

# =========================================================
# PYTHON SORTING CONVENTIONS
# =========================================================


# =========================================================
# SORT IN-PLACE
# =========================================================
# Modifies the original list

nums = [5, 2, 8, 1]

nums.sort()

# nums => [1, 2, 5, 8]


# =========================================================
# SORTED COPY
# =========================================================
# Returns a new sorted list

nums = [5, 2, 8, 1]

sorted_nums = sorted(nums)

# nums         => unchanged
# sorted_nums  => [1, 2, 5, 8]


# =========================================================
# DESCENDING ORDER
# =========================================================

nums.sort(reverse=True)

sorted_nums = sorted(nums, reverse=True)


# =========================================================
# SORT USING CUSTOM KEY
# =========================================================
# Sort by absolute value

nums = [-4, 1, -2, 3]

nums.sort(key=abs)

# nums => [1, -2, 3, -4]


# =========================================================
# SORT TUPLES / PAIRS
# =========================================================

pairs = [(1, 5), (3, 2), (2, 8)]

# Sort by first value
pairs.sort(key=lambda x: x[0])

# Sort by second value
pairs.sort(key=lambda x: x[1])


# =========================================================
# SORT MULTIPLE VALUES
# =========================================================

pairs = [(1, 5), (1, 2), (2, 1)]

# Sort by first value, then second value
pairs.sort(key=lambda x: (x[0], x[1]))


# =========================================================
# SORT STRINGS BY LENGTH
# =========================================================

words = ["apple", "hi", "banana"]

words.sort(key=len)


# =========================================================
# SORT OBJECTS
# =========================================================

# students.sort(key=lambda s: s.gpa)


# =========================================================
# COMMON INTERVIEW PATTERN
# =========================================================
# Sort one list based on another value

position = [10, 8, 0, 5]
speed = [2, 4, 1, 1]

cars = list(zip(position, speed))

cars.sort(reverse=True)

# cars => [(10,2), (8,4), (5,1), (0,1)]


# =========================================================
# ITERATE SORTED WITHOUT MODIFYING ORIGINAL
# =========================================================

for x in sorted(nums):
    pass


# =========================================================
# STABLE SORT
# =========================================================
# Python sorting is stable.
# Equal elements preserve original order.


# =========================================================
# COMPLEXITY
# =========================================================
# Python uses Timsort
#
# Time:
# O(n log n)
#
# Best case:
# O(n)
#
# Space:
# O(n)